// Generated by tools/gen_webp_fixtures.py — do not edit.

#include "render/decoders/selftest_webp_fixtures.h"

#include <stddef.h>

static const WebpProbePt wp_flat[] = {{0,0,0xFF1E909Bu}, {11,0,0xFF1E909Bu}, {0,8,0xFF1E909Bu}, {11,8,0xFF1E909Bu}, {6,4,0xFF1E909Bu}, {3,2,0xFF1E909Bu}, {9,2,0xFF1E909Bu}, {3,6,0xFF1E909Bu}, {9,6,0xFF1E909Bu}, {3,3,0xFF1E909Bu}, {6,8,0xFF1E909Bu}, {9,8,0xFF1E909Bu}};
static const WebpProbePt wp_gradient[] = {{0,0,0xFF000000u}, {47,0,0xFFEB005Eu}, {0,31,0xFF00F83Eu}, {47,31,0xFFEBF89Cu}, {24,16,0xFF788050u}, {12,8,0xFF3C4028u}, {36,8,0xFFB44058u}, {12,24,0xFF3CC048u}, {36,24,0xFFB4C078u}, {12,10,0xFF3C502Cu}, {24,31,0xFF78F86Eu}, {36,31,0xFFB4F886u}};
static const WebpProbePt wp_palette[] = {{0,0,0xFFE42828u}, {39,0,0xFFFAF03Cu}, {0,27,0xFFFAF03Cu}, {39,27,0xFFE42828u}, {20,14,0xFF28C83Cu}, {10,7,0xFFE42828u}, {30,7,0xFF0A0A0Au}, {10,21,0xFF0A0A0Au}, {30,21,0xFFE42828u}, {10,9,0xFF28C83Cu}, {20,27,0xFFE42828u}, {30,27,0xFF323CE6u}};
static const WebpProbePt wp_alpha[] = {{0,0,0x00000000u}, {23,0,0x14DC5ACFu}, {0,15,0x00000000u}, {23,15,0x14DC5ACFu}, {12,8,0x90DC5A6Cu}, {6,4,0x48DC5A36u}, {18,4,0xD8DC5AA2u}, {6,12,0x48DC5A36u}, {18,12,0xD8DC5AA2u}, {6,5,0x48DC5A36u}, {12,15,0x90DC5A6Cu}, {18,15,0xD8DC5AA2u}};
static const WebpProbePt wp_predictor[] = {{0,0,0xFF8FB964u}, {63,0,0xFF95B368u}, {0,47,0xFF92B666u}, {63,47,0xFF97B169u}, {32,24,0xFF84C45Cu}, {16,12,0xFF85C35Du}, {48,12,0xFF8CBC62u}, {16,36,0xFF88C05Fu}, {48,36,0xFF8EBA63u}, {16,16,0xFF84C45Cu}, {32,47,0xFF8EBA63u}, {48,47,0xFF92B666u}};
static const WebpProbePt wp_cache[] = {{0,0,0x80DC94DCu}, {95,0,0xFF5D765Du}, {0,71,0xFF693BB0u}, {95,71,0xFFA54EECu}, {48,36,0x808ACEAEu}, {24,18,0x80D69AE8u}, {72,18,0xFFF42406u}, {24,54,0xFF30A866u}, {72,54,0x807098A6u}, {24,24,0xFF623E7Au}, {48,71,0x807183B8u}, {72,71,0xFFA028E7u}};
static const WebpProbePt wp_meta[] = {{0,0,0xFF002800u}, {299,0,0xFF5A1EC8u}, {0,199,0xFFFAFAF5u}, {299,199,0xFF56288Eu}, {150,100,0xFF5A1EC8u}, {75,50,0xFFFAFAF5u}, {225,50,0xFF5A1EC8u}, {75,150,0xC814E1B4u}, {225,150,0xFFC2282Cu}, {75,66,0xFFFAFAF5u}, {150,199,0xFF5A1EC8u}, {225,199,0xFFC2288Eu}};
static const WebpProbePt wp_pil_bench[] = {{0,0,0xFF000000u}, {265,0,0xFFE5093Fu}, {0,199,0xFF557D71u}, {265,199,0xFF3A86A2u}, {133,100,0xFF9D1127u}, {66,50,0xFFD08810u}, {199,50,0xFF410DB3u}, {66,150,0xFFFC14CCu}, {199,150,0xFF6D9937u}, {66,66,0xFF003800u}, {133,199,0xFFC602CEu}, {199,199,0xFF004400u}};

const WebpProbe webp_probes[] = {
        {0, 12, wp_flat},
        {1, 12, wp_gradient},
        {2, 12, wp_palette},
        {3, 12, wp_alpha},
        {4, 12, wp_predictor},
        {5, 12, wp_cache},
        {6, 12, wp_meta},
        {7, 12, wp_pil_bench},
};

const int webp_probes_len = 8;
