// GENERATED by tools/gen_ico_fixtures.py - do not edit.
#ifndef PLUTO_SELFTEST_ICO_FIXTURES_H
#define PLUTO_SELFTEST_ICO_FIXTURES_H

#include <stddef.h>
#include <stdint.h>

typedef struct { int x, y, v; } IcoProbe;

extern const unsigned char fx_i_1bpp[];
#define FX_I_I_1BPP_LEN 146
#define FX_I_I_1BPP_W 11
#define FX_I_I_1BPP_H 5
#define FX_I_I_1BPP_CK 0xEB4AFE76u
extern const IcoProbe fx_ip_i_1bpp[];
extern const int fx_ip_i_1bpp_len;
extern const unsigned char fx_i_24bpp_masked[];
#define FX_I_I_24BPP_MASKED_LEN 858
#define FX_I_I_24BPP_MASKED_W 12
#define FX_I_I_24BPP_MASKED_H 10
#define FX_I_I_24BPP_MASKED_CK 0x11C15092u
extern const IcoProbe fx_ip_i_24bpp_masked[];
extern const int fx_ip_i_24bpp_masked_len;
extern const unsigned char fx_i_32bpp[];
#define FX_I_I_32BPP_LEN 2234
#define FX_I_I_32BPP_W 16
#define FX_I_I_32BPP_H 16
#define FX_I_I_32BPP_CK 0xCED081D2u
extern const IcoProbe fx_ip_i_32bpp[];
extern const int fx_ip_i_32bpp_len;
extern const unsigned char fx_i_4bpp[];
#define FX_I_I_4BPP_LEN 290
#define FX_I_I_4BPP_W 9
#define FX_I_I_4BPP_H 7
#define FX_I_I_4BPP_CK 0x04E37693u
extern const IcoProbe fx_ip_i_4bpp[];
extern const int fx_ip_i_4bpp_len;
extern const unsigned char fx_i_8bpp_nomask[];
#define FX_I_I_8BPP_NOMASK_LEN 1642
#define FX_I_I_8BPP_NOMASK_W 20
#define FX_I_I_8BPP_NOMASK_H 14
#define FX_I_I_8BPP_NOMASK_CK 0x81C450FFu
extern const IcoProbe fx_ip_i_8bpp_nomask[];
extern const int fx_ip_i_8bpp_nomask_len;
extern const unsigned char fx_i_cursor[];
#define FX_I_I_CURSOR_LEN 338
#define FX_I_I_CURSOR_W 7
#define FX_I_I_CURSOR_H 5
#define FX_I_I_CURSOR_CK 0x049C6B45u
extern const IcoProbe fx_ip_i_cursor[];
extern const int fx_ip_i_cursor_len;
extern const unsigned char fx_i_multi[];
#define FX_I_I_MULTI_LEN 4002
#define FX_I_I_MULTI_W 16
#define FX_I_I_MULTI_H 16
#define FX_I_I_MULTI_CK 0x40900874u
extern const IcoProbe fx_ip_i_multi[];
extern const int fx_ip_i_multi_len;
extern const unsigned char fx_i_png_entry[];
#define FX_I_I_PNG_ENTRY_LEN 751
#define FX_I_I_PNG_ENTRY_W 20
#define FX_I_I_PNG_ENTRY_H 20
#define FX_I_I_PNG_ENTRY_CK 0x987AEF35u
extern const IcoProbe fx_ip_i_png_entry[];
extern const int fx_ip_i_png_entry_len;
extern const unsigned char fx_i_png_fallback[];
#define FX_I_I_PNG_FALLBACK_LEN 829
#define FX_I_I_PNG_FALLBACK_W 12
#define FX_I_I_PNG_FALLBACK_H 9
#define FX_I_I_PNG_FALLBACK_CK 0x501C5103u
extern const IcoProbe fx_ip_i_png_fallback[];
extern const int fx_ip_i_png_fallback_len;
extern const unsigned char fx_i_scaled[];
#define FX_I_I_SCALED_LEN 272282
#define FX_I_I_SCALED_W 266
#define FX_I_I_SCALED_H 200
#define FX_I_I_SCALED_CK 0x78C7C5E0u
extern const IcoProbe fx_ip_i_scaled[];
extern const int fx_ip_i_scaled_len;
extern const unsigned char fx_i_topdown[];
#define FX_I_I_TOPDOWN_LEN 762
#define FX_I_I_TOPDOWN_W 10
#define FX_I_I_TOPDOWN_H 8
#define FX_I_I_TOPDOWN_CK 0x5BAC938Cu
extern const IcoProbe fx_ip_i_topdown[];
extern const int fx_ip_i_topdown_len;
extern const unsigned char fx_ig_bad_reserved[];
#define FX_IG_BAD_RESERVED_LEN 218
extern const unsigned char fx_ig_bad_type[];
#define FX_IG_BAD_TYPE_LEN 218
extern const unsigned char fx_ig_count_zero[];
#define FX_IG_COUNT_ZERO_LEN 202
extern const unsigned char fx_ig_no_entries[];
#define FX_IG_NO_ENTRIES_LEN 22
extern const unsigned char fx_ig_all_fail_dib[];
#define FX_IG_ALL_FAIL_DIB_LEN 1226

#endif
