// GENERATED by tools/gen_svg_fixtures.py - do not edit.
#ifndef PLUTO_SELFTEST_SVG_FIXTURES_H
#define PLUTO_SELFTEST_SVG_FIXTURES_H

#include <stddef.h>
#include <stdint.h>

typedef struct { int x, y, v; } SvgProbe;

extern const char fx_s_arc[];
#define FX_S_ARC_LEN 100
#define FX_S_ARC_W 48
#define FX_S_ARC_H 48
#define FX_S_ARC_CK 0xAE0C14D1u
#define FX_S_ARC_DRAWN 2
extern const SvgProbe fx_sp_arc[];
#define FX_SP_ARC_LEN 12
extern const char fx_s_bench[];
#define FX_S_BENCH_LEN 286
#define FX_S_BENCH_W 192
#define FX_S_BENCH_H 192
#define FX_S_BENCH_CK 0x3AF3BC2Fu
#define FX_S_BENCH_DRAWN 6
extern const SvgProbe fx_sp_bench[];
#define FX_SP_BENCH_LEN 12
extern const char fx_s_comments[];
#define FX_S_COMMENTS_LEN 370
#define FX_S_COMMENTS_W 40
#define FX_S_COMMENTS_H 40
#define FX_S_COMMENTS_CK 0x778C7E39u
#define FX_S_COMMENTS_DRAWN 2
extern const SvgProbe fx_sp_comments[];
#define FX_SP_COMMENTS_LEN 12
extern const char fx_s_nested_skip[];
#define FX_S_NESTED_SKIP_LEN 304
#define FX_S_NESTED_SKIP_W 80
#define FX_S_NESTED_SKIP_H 80
#define FX_S_NESTED_SKIP_CK 0x23BE9796u
#define FX_S_NESTED_SKIP_DRAWN 3
extern const SvgProbe fx_sp_nested_skip[];
#define FX_SP_NESTED_SKIP_LEN 12
extern const char fx_s_path_basic[];
#define FX_S_PATH_BASIC_LEN 104
#define FX_S_PATH_BASIC_W 64
#define FX_S_PATH_BASIC_H 64
#define FX_S_PATH_BASIC_CK 0x22F6C3D5u
#define FX_S_PATH_BASIC_DRAWN 2
extern const SvgProbe fx_sp_path_basic[];
#define FX_SP_PATH_BASIC_LEN 12
extern const char fx_s_path_curves[];
#define FX_S_PATH_CURVES_LEN 103
#define FX_S_PATH_CURVES_W 128
#define FX_S_PATH_CURVES_H 64
#define FX_S_PATH_CURVES_CK 0xAFE1FA86u
#define FX_S_PATH_CURVES_DRAWN 1
extern const SvgProbe fx_sp_path_curves[];
#define FX_SP_PATH_CURVES_LEN 12
extern const char fx_s_rects[];
#define FX_S_RECTS_LEN 328
#define FX_S_RECTS_W 96
#define FX_S_RECTS_H 96
#define FX_S_RECTS_CK 0xC339D83Du
#define FX_S_RECTS_DRAWN 2
extern const SvgProbe fx_sp_rects[];
#define FX_SP_RECTS_LEN 12
extern const char fx_s_shapes[];
#define FX_S_SHAPES_LEN 213
#define FX_S_SHAPES_W 80
#define FX_S_SHAPES_H 80
#define FX_S_SHAPES_CK 0x6307F082u
#define FX_S_SHAPES_DRAWN 5
extern const SvgProbe fx_sp_shapes[];
#define FX_SP_SHAPES_LEN 12
extern const char fx_s_style_attr[];
#define FX_S_STYLE_ATTR_LEN 265
#define FX_S_STYLE_ATTR_W 80
#define FX_S_STYLE_ATTR_H 80
#define FX_S_STYLE_ATTR_CK 0x7D2F3C51u
#define FX_S_STYLE_ATTR_DRAWN 2
extern const SvgProbe fx_sp_style_attr[];
#define FX_SP_STYLE_ATTR_LEN 12
extern const char fx_s_use_defs[];
#define FX_S_USE_DEFS_LEN 171
#define FX_S_USE_DEFS_W 80
#define FX_S_USE_DEFS_H 80
#define FX_S_USE_DEFS_CK 0x95BC21BDu
#define FX_S_USE_DEFS_DRAWN 3
extern const SvgProbe fx_sp_use_defs[];
#define FX_SP_USE_DEFS_LEN 12
extern const char fx_s_viewbox_offset[];
#define FX_S_VIEWBOX_OFFSET_LEN 137
#define FX_S_VIEWBOX_OFFSET_W 80
#define FX_S_VIEWBOX_OFFSET_H 80
#define FX_S_VIEWBOX_OFFSET_CK 0xCE89D7C9u
#define FX_S_VIEWBOX_OFFSET_DRAWN 2
extern const SvgProbe fx_sp_viewbox_offset[];
#define FX_SP_VIEWBOX_OFFSET_LEN 12
extern const char fx_sg_no_svg[];
#define FX_SG_NO_SVG_LEN 16
extern const char fx_sg_zero_drawn[];
#define FX_SG_ZERO_DRAWN_LEN 84
extern const char fx_sg_bad_dims[];
#define FX_SG_BAD_DIMS_LEN 73
extern const char fx_sg_trunc_tag[];
#define FX_SG_TRUNC_TAG_LEN 46

#endif
