// Generated by tools/gen_jpeg_fixtures.py — do not edit.

#include "render/decoders/selftest_jpeg_fixtures.h"

static const JpegProbePt jp_flat[] = {{0,0,128}, {63,47,128}, {32,24,128}, {16,24,128}, {48,24,128}, {8,6,128}, {62,16,128}, {32,45,128}};
static const JpegProbePt jp_dcstripes[] = {{0,0,0}, {239,159,255}, {120,80,255}, {60,80,255}, {180,80,255}, {30,20,255}, {238,53,85}, {120,157,255}};
static const JpegProbePt jp_acblocks[] = {{0,0,96}, {31,23,166}, {16,12,102}, {8,12,160}, {24,12,95}, {4,3,96}, {30,8,156}, {16,21,128}};
static const JpegProbePt jp_restart[] = {{0,0,104}, {159,143,152}, {80,72,136}, {40,72,120}, {120,72,152}, {20,18,136}, {158,48,152}, {80,141,136}};
static const JpegProbePt jp_sub420[] = {{0,0,80}, {127,95,144}, {64,48,176}, {32,48,112}, {96,48,112}, {16,12,142}, {126,32,116}, {64,93,142}};
static const JpegProbePt jp_prog_dc[] = {{0,0,107}, {95,79,161}, {48,40,137}, {24,40,137}, {72,40,137}, {12,10,113}, {94,26,125}, {48,77,161}};
static const JpegProbePt jp_prog_multi[] = {{0,0,107}, {95,79,161}, {48,40,137}, {24,40,137}, {72,40,137}, {12,10,113}, {94,26,125}, {48,77,161}};
static const JpegProbePt jp_prog_refine[] = {{0,0,48}, {63,47,128}, {32,24,128}, {16,24,48}, {48,24,208}, {8,6,88}, {62,16,208}, {32,45,208}};

const JpegProbe jpeg_probes[] = {
    {0, 8, jp_flat},
    {1, 8, jp_dcstripes},
    {2, 8, jp_acblocks},
    {3, 8, jp_restart},
    {4, 8, jp_sub420},
    {5, 8, jp_prog_dc},
    {6, 8, jp_prog_multi},
    {7, 8, jp_prog_refine},
};
