// GENERATED by tools/gen_svg_fixtures.py - do not edit.
#include "render/decoders/selftest_svg_fixtures.h"

const char fx_s_arc[] = "<svg viewBox=\"0 0 24 24\"><path d=\"M3 21 A 8 8 0 0 1 21 21 Z\"/><path d=\"M2 4 a5 5 0 0 0 10 0\"/></svg>";
const int fx_s_arc_len = 100;
const SvgProbe fx_sp_arc[] = {{4,8,0}, {5,8,0}, {6,8,0}, {7,8,0}, {8,8,0}, {9,8,0}, {10,8,0}, {11,8,0}, {12,8,0}, {13,8,0}, {14,8,0}, {15,8,0}};

const char fx_s_bench[] = "<svg viewBox=\"0 0 96 96\"><rect x=\"4\" y=\"4\" width=\"88\" height=\"88\" rx=\"6\"/><circle cx=\"30\" cy=\"34\" r=\"14\"/><ellipse cx=\"66\" cy=\"34\" rx=\"16\" ry=\"9\"/><path d=\"M12 70 C 24 58 36 82 48 70 S 72 58 84 70\"/><polygon points=\"20,88 40,78 60,86 76,80\"/><line x1=\"4\" y1=\"52\" x2=\"92\" y2=\"52\"/></svg>";
const int fx_s_bench_len = 286;
const SvgProbe fx_sp_bench[] = {{11,8,0}, {12,8,0}, {13,8,0}, {14,8,0}, {15,8,0}, {16,8,0}, {17,8,0}, {18,8,0}, {19,8,0}, {20,8,0}, {21,8,0}, {22,8,0}};

const char fx_s_comments[] = "<?xml version=\"1.0\" encoding=\"UTF-8\"?><!DOCTYPE svg PUBLIC \"-//W3C//DTD SVG 1.1//EN\" \"http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd\"><!-- <rect x=\"0\" y=\"0\" width=\"999\" height=\"999\"/> --><![CDATA[ <rect x=\"1\" y=\"1\" width=\"50\" height=\"50\"/> ]]><svg viewBox=\"0 0 20 20\"><rect x=\"2\" y=\"2\" width=\"10\" height=\"8\"/><!-- inner comment --><circle cx=\"15\" cy=\"15\" r=\"3\"/></svg>";
const int fx_s_comments_len = 370;
const SvgProbe fx_sp_comments[] = {{4,4,0}, {5,4,0}, {6,4,0}, {7,4,0}, {8,4,0}, {9,4,0}, {10,4,0}, {11,4,0}, {12,4,0}, {13,4,0}, {14,4,0}, {15,4,0}};

const char fx_s_nested_skip[] = "<svg viewBox=\"0 0 40 40\"><g display=\"none\"><rect x=\"2\" y=\"2\" width=\"10\" height=\"10\"/><g visibility=\"hidden\"><circle cx=\"30\" cy=\"10\" r=\"4\"/></g></g><g><line x1=\"2\" y1=\"30\" x2=\"30\" y2=\"30\"/><symbol><rect x=\"34\" y=\"2\" width=\"4\" height=\"4\"/></symbol></g><switch><circle cx=\"10\" cy=\"10\" r=\"2\"/></switch></svg>";
const int fx_s_nested_skip_len = 304;
const SvgProbe fx_sp_nested_skip[] = {{68,4,0}, {69,4,0}, {70,4,0}, {71,4,0}, {72,4,0}, {73,4,0}, {74,4,0}, {75,4,0}, {68,5,0}, {75,5,0}, {68,6,0}, {75,6,0}};

const char fx_s_path_basic[] = "<svg viewBox=\"0 0 32 32\"><path d=\"M4 4 L12 8 H20 V16 Z M22 6 l4 4 h4 v6\"/><path d=\"M2 28 h8 v-6\"/></svg>";
const int fx_s_path_basic_len = 104;
const SvgProbe fx_sp_path_basic[] = {{8,8,0}, {9,8,0}, {9,9,0}, {10,9,0}, {11,9,0}, {10,10,0}, {11,10,0}, {12,10,0}, {13,10,0}, {12,11,0}, {14,11,0}, {15,11,0}};

const char fx_s_path_curves[] = "<svg viewBox=\"0 0 64 32\"><path d=\"M2 28 C 2-8.264 12e0 4 20 8 S 30 2 38 10 Q 44 0 50 8 T 60 12\"/></svg>";
const int fx_s_path_curves_len = 103;
const SvgProbe fx_sp_path_curves[] = {{0,0,0}, {1,0,0}, {2,0,0}, {3,0,0}, {8,0,0}, {0,1,0}, {1,1,0}, {2,1,0}, {3,1,0}, {4,1,0}, {5,1,0}, {8,1,0}};

const char fx_s_rects[] = "<?xml version=\"1.0\"?>\n<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 48 48\" width=\"48\" height=\"48\">\n<rect x=\"4\" y=\"4\" width=\"16\" height=\"10\"/>\n<rect x=\"26\" y=\"6\" width=\"14\" height=\"14\" rx=\"3\"/>\n<rect x=\"6\" y=\"22\" width=\"12\" height=\"8\" fill=\"none\"/>\n<g display=\"none\"><rect x=\"20\" y=\"20\" width=\"20\" height=\"20\"/></g>\n</svg>";
const int fx_s_rects_len = 328;
const SvgProbe fx_sp_rects[] = {{8,8,0}, {9,8,0}, {10,8,0}, {11,8,0}, {12,8,0}, {13,8,0}, {14,8,0}, {15,8,0}, {16,8,0}, {17,8,0}, {18,8,0}, {19,8,0}};

const char fx_s_shapes[] = "<svg viewBox=\"0 0 40 40\"><circle cx=\"10\" cy=\"10\" r=\"6\"/><ellipse cx=\"28\" cy=\"10\" rx=\"7\" ry=\"4\"/><line x1=\"4\" y1=\"34\" x2=\"18\" y2=\"24\"/><polyline points=\"22,36 30,30 36,32\"/><polygon points=\"6,14 12,18 4,20\"/></svg>";
const int fx_s_shapes_len = 213;
const SvgProbe fx_sp_shapes[] = {{17,8,0}, {18,8,0}, {19,8,0}, {20,8,0}, {21,8,0}, {22,8,0}, {23,8,0}, {15,9,0}, {16,9,0}, {24,9,0}, {25,9,0}, {13,10,0}};

const char fx_s_style_attr[] = "<svg viewBox=\"0 0 40 40\"><rect x=\"2\" y=\"2\" width=\"12\" height=\"8\" style=\"fill:none\"/><rect x=\"20\" y=\"2\" width=\"12\" height=\"8\" fill=\"none\" style=\"fill:black\"/><circle cx=\"8\" cy=\"24\" r=\"5\" style=\"display:none\"/><circle cx=\"24\" cy=\"24\" r=\"5\" style=\"stroke:gray\"/></svg>";
const int fx_s_style_attr_len = 265;
const SvgProbe fx_sp_style_attr[] = {{40,4,0}, {41,4,0}, {42,4,0}, {43,4,0}, {44,4,0}, {45,4,0}, {46,4,0}, {47,4,0}, {48,4,0}, {49,4,0}, {50,4,0}, {51,4,0}};

const char fx_s_use_defs[] = "<svg viewBox=\"0 0 40 40\"><defs><circle id=\"dot\" cx=\"8\" cy=\"8\" r=\"5\"/></defs><use href=\"#dot\"/><use xlink:href=\"#missing\"/><use href=\"#dot\"/><g><use href=\"#dot\"/></g></svg>";
const int fx_s_use_defs_len = 171;
const SvgProbe fx_sp_use_defs[] = {{13,6,0}, {14,6,0}, {15,6,0}, {16,6,0}, {17,6,0}, {18,6,0}, {19,6,0}, {11,7,0}, {12,7,0}, {20,7,0}, {21,7,0}, {10,8,0}};

const char fx_s_viewbox_offset[] = "<svg viewBox=\"10 5 40 40\" width=\"40\" height=\"40\"><rect x=\"12\" y=\"7\" width=\"16\" height=\"10\"/><line x1=\"10\" y1=\"25\" x2=\"46\" y2=\"45\"/></svg>";
const int fx_s_viewbox_offset_len = 137;
const SvgProbe fx_sp_viewbox_offset[] = {{4,4,0}, {5,4,0}, {6,4,0}, {7,4,0}, {8,4,0}, {9,4,0}, {10,4,0}, {11,4,0}, {12,4,0}, {13,4,0}, {14,4,0}, {15,4,0}};

const char fx_sg_no_svg[] = "<div>hello</div>";
const int fx_sg_no_svg_len = 16;

const char fx_sg_zero_drawn[] = "<svg viewBox=\"0 0 20 20\"><defs><rect x=\"2\" y=\"2\" width=\"8\" height=\"8\"/></defs></svg>";
const int fx_sg_zero_drawn_len = 84;

const char fx_sg_bad_dims[] = "<svg width=\"0\" height=\"10\"><rect x=\"1\" y=\"1\" width=\"5\" height=\"5\"/></svg>";
const int fx_sg_bad_dims_len = 73;

const char fx_sg_trunc_tag[] = "<svg viewBox=\"0 0 10 10\"><rect x=\"1\" y=\"1\" wid";
const int fx_sg_trunc_tag_len = 46;

