-- P19 walker test corpus: (name, html, baseUrl, detailsOpen, expectThrow).
-- Shared by run.lua (Lua pipeline capture) and gen_inputs.lua (C header).
return {
  { name = "h1-headings",
    html = "<h1>Hello</h1><h2 style='text-align: right'>Two</h2><h6 id='x'>Six</h6>after" },
  { name = "p-divs",
    html = "<p>one</p><div align='center'>two <b>bold</b></div><section>s</section><aside>a</aside>" },
  { name = "blockquote", html = "<blockquote>q<b>uote</b></blockquote>" },
  { name = "center-marquee", html = "<center>c</center><marquee>m</marquee>" },
  { name = "br-hr-wbr", html = "a<br>b<hr>c<wbr>d" },
  { name = "pre-code", html = "<pre>  a\n  b  </pre><xmp><i>raw</i></xmp>" },
  { name = "inline-styles",
    html = "<b>B</b><i>I</i><u>U</u><code>C</code><mark>M</mark><small>s</small><big>bg</big><sub>sub</sub><sup>sup</sup><del>del</del><q>q</q><abbr title='x'>ab</abbr>" },
  { name = "span-font",
    html = "<span style='font-weight:bold; color:white'>sw</span><font size='+1'>big</font><font size='-1'>small</font><time datetime='2024-01-01'></time><data value='42'></data>" },
  { name = "links",
    html = "<a href='/one'>One</a><a href='#x'>frag</a><a href='javascript:void(0)'>js</a><a href='http://a.b/c' title='T'>short</a><a>bare</a>" },
  { name = "lists",
    html = "<ul><li>a</li><li value='5'>b</li><li>c</li></ul><ol start='3' type='a'><li>x</li><li>y</li></ol>" },
  { name = "dl", html = "<dl><dt>Term</dt><dd>Def</dd><dt>T2</dt></dl>" },
  { name = "img-figure",
    html = "<img src='pic.png' width='200' height='100' usemap='#m' alt='Pic'><figure><figcaption>Cap text</figcaption><img src='f.png' width='50' height='30'></figure>" },
  { name = "img-in-link",
    html = "<a href='/gallery'><img src='t.png' width='40' height='30' alt='Thumb'></a>" },
  { name = "image-data-src",
    html = "<img data-src='lazy.png' width='90' height='45'><img src='tracking.png'><img src='beacon.gif'><img srcset='a.png 1x, b.png 2x' width='10' height='10'>" },
  { name = "map-area",
    html = "<map name='m'><area shape='rect' coords='0,0,50,50' href='/go' alt='Go'><area shape='circle' coords='10,10,5'></map>" },
  { name = "table",
    html = "<table border='1' align='center'><caption>Cap</caption><tr><th colspan='2'>H</th></tr><tr><td>a</td><td align='right'>b</td></tr></table>" },
  { name = "tbody-th",
    html = "<table><thead><tr><th>H1</th></tr></thead><tbody><tr><td>1</td></tr></tbody></table>" },
  { name = "forms",
    html = "<form action='/submit' method='POST'><input type='hidden' name='h' value='1'><input type='checkbox' name='c' value='v' checked><input type='radio' name='r' checked><input name='q' placeholder='Search'><input type='submit' value='Go'><button>Click</button></form>" },
  { name = "textarea",
    html = "<form><textarea name='ta' cols='30' rows='4'>default text</textarea></form>" },
  { name = "select",
    html = "<form><select name='s'><option>One</option><option value='2' selected>Two</option><option disabled>Three</option></select></form>" },
  { name = "fieldset-details",
    html = "<fieldset disabled><legend>L</legend><input name='x'><input name='y' disabled></fieldset><details open><summary>Sum</summary><p>body</p></details><dialog open><p>dlg</p></dialog>" },
  { name = "media",
    html = "<video src='v.mp4' width='300' height='100'><source src='fallback.webm'></video><iframe src='https://frame.example/'> </iframe><audio></audio><progress value='2' max='5'></progress><meter value='3' max='10'></meter>" },
  { name = "math",
    html = "<math><mi>x</mi><mo>=</mo><mfrac><mn>1</mn><mn>2</mn></mfrac><msup><mi>y</mi><mn>2</mn></msup><msqrt><mn>9</mn></msqrt></math>" },
  { name = "svg", html = "<svg width='50' height='20'><rect width='10' height='10'/></svg>" },
  { name = "script-title",
    html = "<title>Ignored In Flow</title><script>var x = 1;</script><style>p{color:red}</style><p>visible</p>" },
  { name = "noscript",
    html = "<noscript>ns</noscript><template><p>tpl</p></template><p>after</p>" },
  { name = "hidden-inert",
    html = "<div hidden>gone</div><div style='display:none'>gone2</div><div inert>inert <input type='submit' value='X'></div>" },
  { name = "nested-overflow", html = string.rep("<div>", 5) .. "deep" .. string.rep("</div>", 5) },
  { name = "empty-page", html = "" },
  { name = "empty-tree", html = "   " },
  { name = "in-table-link",
    html = "<table><tr><td><a href='/c'>cell link</a></td></tr></table>" },
  { name = "figure-caption-only", html = "<figure><figcaption>Only caption</figcaption></figure>" },
  { name = "br-in-pre", html = "<pre>line1<br>line2</pre>" },
  { name = "details-open-override",
    html = "<details id='a'><summary>S1</summary><p>p1</p></details><details><summary>S2</summary><p>p2</p></details>",
    detailsOpen = { d1 = false, d2 = true } },
  { name = "dl-nested", html = "<dl><dt>outer<dl><dt>inner</dt><dd>id</dd></dl></dt></dl>" },
  { name = "wbr-br-inline", html = "<p>foo<wbr>bar<br>baz</p>" },
  { name = "pre-multiline", html = "<pre>l1\nl2\nl3</pre>" },
  { name = "img-no-src",
    html = "<img alt='NoSrc'><img src='beacon.gif'><img srcset='1x.png 1x, 2x.png 2x' alt='Ss'>" },
  { name = "media-title",
    html = "<video src='v.mp4' title='My Video'></video><iframe title='Frame'></iframe><embed> " },
  { name = "placeholder-href",
    html = "<a href='/watch'><iframe src='https://frame.example/x' width='200' height='100'></iframe></a><portal src='/portal'>p</portal>" },
  { name = "placeholder-no-src",
    html = "<video></video><audio></audio><canvas></canvas><object></object>" },
  { name = "fencedframe", html = "<fencedframe width='100' height='50'>x</fencedframe>" },
  { name = "invalid-attrs",
    html = "<h1 invalid='1'>H</h1><p style='text-align: justify'>J</p><p align='bad'>X</p>" },
  { name = "invert", html = "<p style='color: #fff; background-color: #000000'>inv</p>" },
  { name = "list-item-value", html = "<ol start='10' reversed><li value='7'>a</li><li>b</li></ol>" },
  { name = "li-no-list", html = "<li>orphan</li>", expectThrow = true },
  { name = "hr-in-div", html = "<div>a<hr>b</div>" },
  { name = "span-nested", html = "<span style='font-style:italic'><span style='font-weight:700'>both</span></span>" },
  { name = "q-quotes", html = "<q>double</q>" },
}