-- Generate Source/html/p19_inputs.h from cases.lua (C-escaped, so the C
-- battery never re-transcribes inputs by hand).
local function cesc(s)
  s = tostring(s)
  s = s:gsub("\\", "\\\\"):gsub('"', '\\"'):gsub("\n", "\\n"):gsub("\r", "\\r"):gsub("\t", "\\t")
  return s
end

local out = {}
out[#out + 1] = "/* Generated by tests/lua_reference/p19_walker/gen_inputs.lua from cases.lua."
out[#out + 1] = " * Do not edit by hand — regenerate with: lua tests/lua_reference/p19_walker/gen_inputs.lua > Source/html/p19_inputs.h"
out[#out + 1] = " */"
out[#out + 1] = "#ifndef PLUTO_P19_INPUTS_H"
out[#out + 1] = "#define PLUTO_P19_INPUTS_H"
out[#out + 1] = ""
out[#out + 1] = "typedef struct"
out[#out + 1] = "{"
out[#out + 1] = "    const char *name;"
out[#out + 1] = "    const char *html;"
out[#out + 1] = "    const char *base;"
out[#out + 1] = "    const int *details; /* detailsOpen overrides; NULL when none */"
out[#out + 1] = "    int detailsCount;"
out[#out + 1] = "    int expectThrow;"
out[#out + 1] = "} P19Input;"
out[#out + 1] = ""

local cases = dofile("tests/lua_reference/p19_walker/cases.lua")
local decls = {}
local rows = {}
for ci, c in ipairs(cases) do
  local arrName = string.format("p19_det_c%02d", ci)
  -- detailsOpen keys are d1..dN; emit a positional array (index N-1 -> dN).
  local det = c.detailsOpen
  local detName = "NULL"
  if det then
    local n = 0
    for k in pairs(det) do
      local idx = tonumber(string.match(k, "^d(%d+)$"))
      if idx and idx > n then n = idx end
    end
    decls[#decls + 1] = string.format("static const int %s[] = {%s};", arrName,
      table.concat({ (function()
        local parts = {}
        for i = 1, n do
          parts[#parts + 1] = det["d" .. i] and "1" or "0"
        end
        return table.unpack(parts)
      end)() }, ", "))
    detName = arrName
    rows[#rows + 1] = string.format("    { \"%s\", \"%s\", \"%s\", %s, %d, %d },",
      c.name, cesc(c.html), cesc(c.baseUrl or "https://example.com/"), detName, n,
      c.expectThrow and 1 or 0)
  else
    rows[#rows + 1] = string.format("    { \"%s\", \"%s\", \"%s\", NULL, 0, %d },",
      c.name, cesc(c.html), cesc(c.baseUrl or "https://example.com/"), c.expectThrow and 1 or 0)
  end
end

for _, d in ipairs(decls) do out[#out + 1] = d end
out[#out + 1] = ""
out[#out + 1] = "static const P19Input p19_inputs[] = {"
for _, r in ipairs(rows) do out[#out + 1] = r end
out[#out + 1] = "};"
out[#out + 1] = "#define P19_INPUT_COUNT " .. #cases
out[#out + 1] = ""
out[#out + 1] = "#endif /* PLUTO_P19_INPUTS_H */"

print(table.concat(out, "\n"))